//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderGenerator.Web.GenerationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerationResponse", Namespace="http://schemas.datacontract.org/2004/07/ProviderGenerator.Messaging.Model")]
    [System.SerializableAttribute()]
    public partial class GenerationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrors {
            get {
                return this.HasErrorsField;
            }
            set {
                if ((this.HasErrorsField.Equals(value) != true)) {
                    this.HasErrorsField = value;
                    this.RaisePropertyChanged("HasErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://marc-hi.ca/xmlns/patgensvc", ConfigurationName="GenerationService.IGenerationService")]
    public interface IGenerationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="GenerateProviders", ReplyAction="http://marc-hi.ca/xmlns/patgensvc/IGenerationService/GenerateProvidersResponse")]
        ProviderGenerator.Web.GenerationService.GenerateProvidersResponse GenerateProviders(ProviderGenerator.Web.GenerationService.GenerateProvidersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateProviders", WrapperNamespace="http://marc-hi.ca/xmlns/patgensvc", IsWrapped=true)]
    public partial class GenerateProvidersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marc-hi.ca/xmlns/patgensvc", Order=0)]
        public int count;
        
        public GenerateProvidersRequest() {
        }
        
        public GenerateProvidersRequest(int count) {
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateProvidersResponse", WrapperNamespace="http://marc-hi.ca/xmlns/patgensvc", IsWrapped=true)]
    public partial class GenerateProvidersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marc-hi.ca/xmlns/patgensvc", Order=0)]
        public ProviderGenerator.Web.GenerationService.GenerationResponse GenerateProvidersResult;
        
        public GenerateProvidersResponse() {
        }
        
        public GenerateProvidersResponse(ProviderGenerator.Web.GenerationService.GenerationResponse GenerateProvidersResult) {
            this.GenerateProvidersResult = GenerateProvidersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenerationServiceChannel : ProviderGenerator.Web.GenerationService.IGenerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerationServiceClient : System.ServiceModel.ClientBase<ProviderGenerator.Web.GenerationService.IGenerationService>, ProviderGenerator.Web.GenerationService.IGenerationService {
        
        public GenerationServiceClient() {
        }
        
        public GenerationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProviderGenerator.Web.GenerationService.GenerateProvidersResponse GenerateProviders(ProviderGenerator.Web.GenerationService.GenerateProvidersRequest request) {
            return base.Channel.GenerateProviders(request);
        }
    }
}
